export const FETCH_EXPENSES = "FETCH_EXPENSES";
export const FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS";
export const FETCH_EXPENSES_ERROR = "FETCH_EXPENSES_ERROR";

export const FETCH_BILLS = "FETCH_BILLS";
export const FETCH_BILLS_SUCCESS = "FETCH_BILLS_SUCCESS";
export const FETCH_BILLS_ERROR = "FETCH_BILLS_ERROR";

export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_ERROR = "ADD_EXPENSE_ERROR";

export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_ERROR = "DELETE_EXPENSE_ERROR";

export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const EDIT_EXPENSE_SUCCESS = "EDIT_EXPENSE_SUCCESS";
export const EDIT_EXPENSE_ERROR = "EDIT_EXPENSE_ERROR";

export const EDIT_BILL = "EDIT_BILL";
export const EDIT_BILL_SUCCESS = "EDIT_BILL_SUCCESS";
export const EDIT_BILL_ERROR = "EDIT_BILL_ERROR";

export const SET_MONTH = "SET_MONTH";
