export const FETCH_EXPENSES = "FETCH_EXPENSES";
export const FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS";
export const FETCH_EXPENSES_ERROR = "FETCH_EXPENSES_ERROR";

export const FETCH_FIXED_COSTS = "FETCH_FIXED_COSTS";
export const FETCH_FIXED_COSTS_SUCCESS = "FETCH_FIXED_COSTS_SUCCESS";
export const FETCH_FIXED_COSTS_ERROR = "FETCH_FIXED_COSTS_ERROR";

export const SET_BILL_STATUS = "SET_BILL_STATUS";
